apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: dev-pki
spec:
  secretName: ca-certificate-secret
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - cert sign