apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: exacaple-certificate
  namespace: dev-pki
spec:
  secretName: ca-certificate-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: ca
    kind: Certificate

 


 

