#command: kubectl create secret generic mysql-db-url --from-literal=database=krishna --dry-run=client -o yaml > mysql-db-url.yaml
apiVersion: v1
data:
  database: a3Jpc2huYQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-db-url
