apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-certificate
  namespace: prod-website
spec:
  secretName: website-tls-secret
  dnsNames:
    - example.com
  issuerRef:
    name: ca-certificate
    kind: Certificate


 


 

