apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: staging-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
     containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: password         
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: database         
        # volumeMounts:
        # - name: mysql-pv
        #   mountPath: /var/lib/mysql         
        ports:
        - containerPort: 3306

