apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: prod-website
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql.default:3306
        - name: WORDPRESS_DB_USER
          value: wordpressUser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
        ports:
        - containerPort: 80

