#command: kubectl create secret generic mysql-user-pass  --from-literal=username=krishna --from-literal=password=krishna --dry-run=client -o yaml > mysql-user-pass.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: prod-website
type: Opaque
data:
  password: base64-encoded-db-password
  username: base64-encoded-db-password
