apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: prod-website
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009

